# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Create working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src

# Install application
RUN pip install --no-cache-dir .

# Default command: run MCP server in stdio mode
CMD ["logi-mcp-server", "sse"]